# Rubocop serves as linter and formatter
require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 130
  Exclude:
    - "config/**/**"
    - "encrypt_credentials.rb"

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 150

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "Rakefile"
    - "config.ru"
    - "config/**/**"
    - "bin/*"

Style/StringLiterals:
  Exclude:
    - "Rakefile"
    - "config.ru"
    - "config/**/**"
    - "bin/*"

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"
    - "lib/tasks/*"
    - "config/**/**"
    - "spec/**/**"
    - "db/seeds/*"

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - "bin/*"

Style/SpecialGlobalVars:
  Exclude:
    - "bin/bundle"

Metrics/MethodLength:
  Max: 40
  Exclude:
    - "bin/bundle"

Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - "bin/bundle"

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "db/schema.rb"

Rails/BulkChangeTable:
  Enabled: false

Style/WordArray:
  Exclude:
    - "db/schema.rb"

Rails/Output:
  Exclude:
    - "db/seeds.rb"
    - "db/seeds/**/**"

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - "app/models/order.rb"
    - "app/models/product.rb"
    - "app/models/order_detail.rb"
    - "app/jobs/*"
