name: Assembly Erp

services:
  postgres:
    image: "postgres:15.3-bookworm"
    container_name: erpweb-db
    restart: always
    ports:
      - "3010:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql@15/data

  redis:
    image: redis:latest
    container_name: erpweb-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
