version: "3"
name: simple_erp

services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/pgsql/data
      - ./postgres//lib-data/postgresql.conf:/var/lib/pgsql/data/postgresql.conf:ro
      - ./postgres/lib-data/pg_hba.conf:/var/lib/pgsql/data/pg_hba.conf:ro
    image: erp-postgres
    container_name: postgres-1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      erpweb_network:
        ipv4_address: 172.30.0.100
    ports:
      - "3010:3010"
    command: postgres -c config_file=/var/lib/pgsql/data/postgresql.conf
    restart: always 
  
  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    image: pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@fake.com
      PGADMIN_DEFAULT_PASSWORD: Heavy2Street$
    networks:
      erpweb_network:
        ipv4_address: 172.30.0.150
    ports:
      - "3100:80"

volumes:
  postgres_data:
  pgadmin_data:

networks:
  erpweb_network:
    external: false
    ipam:
      config:
        - subnet: 172.30.0.0/24
