name: simple_erp

services:
  postgres:
    image: "postgres:15.3-bookworm"
    container_name: erpweb-db
    ports:
      - "3010:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql@15/data

  # erpweb:
  #   build:
  #     context: .
  #     dockerfile: ${APP_DOCKERFILE}
  #   volumes:
  #     - erpweb_data:/app
  #     - ./:/app
  #   image: v1-erpweb
  #   container_name: v1-erpweb-1
  #   environment:
  #     - SECRET_KEY_BASE=${SECRET_KEY_BASE}
  #     - DB_HOST=postgres
  #     - DB_PORT=${DB_PORT}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   networks:
  #     erpweb_network:
  #       ipv4_address: 172.30.0.10
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
  #   restart: always 

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    image: pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@fake.com
      PGADMIN_DEFAULT_PASSWORD: Heavy2Street$
    networks:
      erpweb_network:
        ipv4_address: 172.30.0.150
    ports:
      - "3100:80"

volumes:
  postgres_data:
  pgadmin_data:
  # erpweb_data:

networks:
  erpweb_network:
    external: false
    ipam:
      config:
        - subnet: 172.30.0.0/24
