# docker-compose.yml

services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile.dev
    volumes:
      - postgres_data:/var/lib/pgsql/data
      - ./postgres//lib-data/postgresql.conf:/var/lib/pgsql/data/postgresql.conf:ro
      - ./postgres/lib-data/pg_hba.conf:/var/lib/pgsql/data/pg_hba.conf:ro
    image: erp-postgres
    container_name: postgres-1
    environment:
      POSTGRES_USER: master1
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: erpweb_1
    networks:
      erpweb_network:
        ipv4_address: 172.30.0.100
    ports:
      - "3010:3010"
    command: postgres -c config_file=/var/lib/pgsql/data/postgresql.conf
    restart: always 

  erpweb:
    build:
      context: ./erpweb
      dockerfile: Dockerfile
    volumes:
      - erpweb_data:/app
      - ./erpweb:/app
    image: v1-erpweb
    container_name: v1-erpweb-1
    environment:
      - JWT_SECRET_KEY=40081508cad0c366f737d23f74fd6a6a8ccb2091296966ff1bf2cb88714537c03d9395be08be1373d72bf4349edc60487d0c304fe6791ef5ef751634971ee58d
      - SECRET_KEY_BASE=c28896cbf01654b67f7cc564f9d22065d507a2c34664a1684bc7c1d6e6dc35270f66ce8b33d8355324c810f61503febd6739ba15396f970b814c4ce1ab6e09a2
      # - RAILS_ENV=development
      - DB_HOST=postgres
      - DB_PORT=3010
      - POSTGRES_USER=master1
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=erpweb_1
    #  - TYPESENSE_API_KEY=40081508cad0c366f737d23f74fd6a6a8ccb2091296966ff1bf2cb88714537c03d9395be08be1373d72bf4349edc60487d0c304fe6791ef5ef751634971ee58d
    #  - TYPESENSE_SERVER_URL=http://typesense 
    networks:
      erpweb_network:
        ipv4_address: 172.30.0.10
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      #- typesense
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    restart: always 

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    volumes:
      - pgadmin_data:/var/lib/pgadmin
 #     - /etc/letsencrypt/live/pgadmin.db.ngnair.com:/certs:ro
    image: pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@fake.com
      PGADMIN_DEFAULT_PASSWORD: Heavy2Street$
    networks:
      erpweb_network:
        ipv4_address: 172.30.0.150
    ports:
      - "3100:80"
    

  # typesense:
  #   image: typesense/typesense:0.24.0
  #   ports:
  #     - "8108:8108"
  #   environment:
  #     - TYPESENSE_API_KEY=40081508cad0c366f737d23f74fd6a6a8ccb2091296966ff1bf2cb88714537c03d9395be08be1373d72bf4349edc60487d0c304fe6791ef5ef751634971ee58d
  #     - TYPESENSE_DATA_DIR=/data
  #   volumes:
  #     - typesense-data:/data
  #   networks:
  #     - erpweb_network

volumes:
  postgres_data:
  erpweb_data:
  pgadmin_data:
 # typesense-data:

networks:
  erpweb_network:
    external: false
    ipam:
      config:
        - subnet: 172.30.0.0/24

