# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ErrorCardComponent`.
# Please instead update this file by running `bin/tapioca dsl ErrorCardComponent`.


class ErrorCardComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
