# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NavbarLinkComponent`.
# Please instead update this file by running `bin/tapioca dsl NavbarLinkComponent`.


class NavbarLinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
