# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PolyAttributeComponent`.
# Please instead update this file by running `bin/tapioca dsl PolyAttributeComponent`.


class PolyAttributeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
