# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UnderConstructionComponent`.
# Please instead update this file by running `bin/tapioca dsl UnderConstructionComponent`.


class UnderConstructionComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
