source 'https://rubygems.org'

ruby '3.3.1'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.1.3', '>= 7.1.3.2'

gem 'sprockets', '~> 4.0'
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Turbo for real time and partial page loading
gem 'hotwire-rails'

# Add the pg gem
gem 'pg', '~> 1.2'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Use SCSS for stylesheets
gem 'sassc-rails'
gem 'sass-rails', '>= 6'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]
gem 'tailwindcss-rails'

# draper
gem 'draper'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Javascript Runtime
gem 'mini_racer', platforms: :ruby

# Search Feature
# gem 'typesense', '~> 1.0'
# gem 'meilisearch-rails'

# dependency for meilisearch-rails
gem 'csv', '~> 3.1'

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# Preview images in the browser
gem 'image_processing', '~> 1.2'
# gem 'mini_magick'
gem 'ruby-vips', '~> 2.0'

# Use Redis adapter to run Action Cable in production
gem 'redis', '>= 4.0.1'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Documentation Generator
gem 'rswag-api'
gem 'rswag-ui'

# config/routes Device_for
gem 'devise'
gem 'devise-jwt'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# BaseController for API
gem 'jwt'

# for AJAX
gem 'jquery-rails'
# gem 'turbolinks', '~> 5'

# pagination tool
gem 'kaminari'

# Use Active Record enum
gem 'enumerize'

# Culnerability checker
gem 'bundler-audit'

# User Friendly URLs
gem 'friendly_id'

# name said it all
gem 'rails_best_practices'

# as the name says
gem 'traceroute'

# compress js
gem 'uglifier'

gem 'active_storage_validations'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'debug', platforms: %i[mri windows]

  # provide behavior feedback
  gem 'rspec-rails', '~> 6.0.0'

  # feature-rich gem that enhances the debugging
  gem 'pry'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'

  # vulnerability scanner
  gem 'brakeman'

  # listen to update
  gem 'listen', '~> 3.5'

  # Better errors for debugging
  gem 'better_errors'
  gem 'binding_of_caller'

  # Bullet gem for detecting N+1 queries
  gem 'bullet'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end
